var test = require('test');
test.setup();

run("./alter-table.js");
run("./combining-queries.js");
run("./conditions.js");
run("./create-table.js");
run("./create-view.js");
run("./delete.js");
run("./drop-table.js");
run("./functions.js");
run("./helpers.js");
run("./insert.js");
run("./joins.js");
run("./normalize.js");
run("./order.js");
run("./regression.js");
run("./select.js");
run("./table-aliasing.js");
run("./to-query.js");
run("./update.js");
